### ISSUE TITLE
models里的post对象的字段是在哪里定义的，一直没找到

### ISSUE THREAD

**Issue by xw332** [sskyy/twenty#1]
我是指默认的title和category之类的对象字段，没有看到哪里有定义
可能对这套模板还有点不熟，在尝试改成社区的过程中，遇到蛮多小问题
建议多搞一个和post同样类型属性的对象，好比较两者代码上的共性和特性

**Comment by sskyy** [comment]
他们的定义都在 /api/model下面。不过目前的定义文件都是空的，浏览器端发来什么字段，它就存什么。关于它的定义你可以参考下文档 [http://sailsjs.org/#/documentation/concepts/ORM/Attributes.html](http://sailsjs.org/#/documentation/concepts/ORM/Attributes.html) 。之后我们会完善twenty的开发指南，目前人力比较有限，请见谅。

**Comment by xw332** [comment]
特别期待看到论坛的demo，现在正在尝试中，还有点无从下手。。

**Comment by sskyy** [comment]
@xw332  我们正在升级内核中，预计下个月开始会开发多用户的系统，既可以做论坛了：）
