### ISSUE TITLE
login问题：已成功install一个管理员，但再换另一台机器上登录不上去。

### ISSUE THREAD

**Issue by edwardstudy** [sskyy/twenty#2]
情况是这样：
在A机注册成功后，A机登录成功。A机退出登录，B机无法登录，最后A机也无法成功登录了。这是出了什么问题吗？

**Comment by edwardstudy** [comment]
改正问题，一台机子上也有这个问题，即登录登出再登录就报用户名或密码错误。terminal上是
debug: [FIND USER TIME]: 2
[RESPOND ERR]: [ 404, { msg: 'user not found' } ]

**Comment by sskyy** [comment]
登陆使用填的email登陆的，不是用户名。目前我没有重现出你说的问题。

**Comment by edwardstudy** [comment]
谢谢，是这个email的原因。不过你可以尝试一下install之后用Full name登录一下，貌似第一个是可以登录进去的。
